services:
  - name: syledger-api
    type: web
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 8080
    plan: free

  - name: syledger-ws
    type: web
    env: node
    buildCommand: npm install
    startCommand: node ws.js
    envVars:
      - key: PORT
        value: 8081
    plan: free
