services:
  - name: syledger-backend
    type: web
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: "8080"


  - name: syledger-api
    type: static
    buildCommand: ""
    staticPublishPath: "/frontend"
